### ISSUE TITLE
Greeting from Contentful

### ISSUE THREAD

**Issue by Khaledgarbaya** [bandraszyk/contentful-emails#1]
Hi there,

I wanted to say this is a great use case of Contentful, just added it to our [awesome-contentful](https://github.com/contentful-labs/awesome-contentful/pull/18).

BTW I maintain Contentful's js SDKs/integrations so feel free to ping me on GitHub if you need any help regarding anything related to that.

Best,
Khaled

**Comment by bandraszyk** [comment]
Hi Khaled,

I'm glad you like it! We found Contenful as a really useful tool, it simplifies a lot of things related with content management while having only little piece of code on our side. If we come up with any other useful use case we are gonna definitely share it with the community.

Best,
Bandro
